### PR TITLE
Improve Error Handling

### PR DESCRIPTION
**Pull request by Huulamnguyen**
**What does this PR do?**
- First Change: to verify that user do not log in or sign up, but try to access to routes. 
- Second Change: a logged in user try to update username. However, the updated username has already taken. 

**Description of Task to be completed?**
- For the first change: I added GET request for lines (191, 207, 294, 317, 346).
- For second change: If the updated username has already taken, It would raise an error. I applied try/except here and redirect to `users/profile` route.

**How should this be manually tested?**
- Clone the repository.
- For first change: Do not log in or sign up, but try to access to `http://localhost:5000/users/follow/1`, `http://localhost:5000/users/stop-following/1`, `http://localhost:5000/users/delete`, `http://localhost:5000//messages/new`, `http://localhost:5000/messages/<int:message_id>/delete`
- For second change: access to `http://localhost:5000/users/profile`, change to username that has been taken then submit

### CODE REVIEW

**Comment by alexkayabula** [comment]
@Huulamnguyen kindly update the status of this pull request. It being a draft means it is not ready for review. It is also important to make the title of the pull request specific but brief.

**Comment by alexkayabula** [comment]
@Kindly rebase and resolve the merge conflicts. NOTE: It is advisable not to resolve merge conflicts from the remote Git repository.(Resolve the merge conflicts from your local Git)

**Comment by alexkayabula** [comment]
@Kindly rebase and resolve the merge conflicts. NOTE: It is advisable not to resolve merge conflicts from the remote Git repository.(Resolve the merge conflicts from your local Git)

**Comment by Huulamnguyen** [comment]
>  rebase and resolve the merge conflicts. NOTE: It is advisable not to resolve merge conflicts from the remote Git repository.(Resolve the merge conflicts from your local Git)
@alexkayabula I tried to resolve the conflict by local Git Repo. But it showed me everything up-to-date. Then, I tried to resolve by web editor and it was resolved

**Comment by alexkayabula** [comment]
@Kindly rebase and resolve the merge conflicts. NOTE: It is advisable not to resolve merge conflicts from the remote Git repository.(Resolve the merge conflicts from your local Git)

**Comment by alexkayabula** [comment]
@Huulamnguyen , change the title of the pull request to ``Improve error handling``

**Comment by alexkayabula** [comment]
@Huulamnguyen like I had communicated earlier in the mail. Each pull request should only have one related commit message.

> > rebase and resolve the merge conflicts. NOTE: It is advisable not to resolve merge conflicts from the remote Git repository.(Resolve the merge conflicts from your local Git)
> > @alexkayabula I tried to resolve the conflict by local Git Repo. But it showed me everything up-to-date. Then, I tried to resolve by web editor and it was resolved

It is not good practice to resolve merge conflicts from the web editor. You probably rebased wrongly. Below is the workflow I use when rebasing.

```1. git checkout <main branch> ```
```2. git pull origin <main branch>``` 
```3. git checkout <your branch> ```
```4. git rebase <main branch> ```
*If you have conflicts resolve the conflicts* 
```5. git status``` 
```6. git add```
```7. git status ```
```8. git rebase --continue ```
```9. git push origin <your branch>  -f ```

**Comment by alexkayabula** [comment]
@Huulamnguyen , just like i had communicated earlier in mail, it is good practice to always have 1 commit message for each pull request. Kindly squash the 4 commit messages into one.
Use this as a reference [squashing commits into one](https://www.internalpointers.com/post/squash-commits-into-one-git )

**Comment by Huulamnguyen** [comment]
@alexkayabula Hello Alex. I feel confuse when the first time using git workflow like this. I probably messed thing up. I just changed the pull request to `Improve error handling` and squash 4 commit messages into one. I believe I just did it wrong.

**Pull request merged**
